'use strict';
class Game {
  constructor(canvas, map, ui, options={}) {
    this.canvas=canvas; this.ctx=canvas.getContext('2d'); this.map=map; this.mctx=map.getContext('2d'); this.ui=ui;
    this.mission=options.mission||Game.MISSIONS[0]; this.contract=this.mission.contract; this.seed=options.seed||this.mission.seed||5005; this.rng=Game.mulberry32(this.seed); this.onEnd=options.onEnd||(()=>{});
    this.keys={}; this.assist=true; this.running=false; this.paused=false; this.acc=0; this.last=0; this.time=0; this.radioUntil=0; this.damageCd=0; this.dockProgress=0; this.slingshot=null; this.style=1; this.bestSling=0;
    this.telemetry={version:1,seed:this.seed,contract:this.contract.id,mission:this.mission.id,collisions:[],brakeTicks:0,strafeTicks:0,assistToggles:0,slingshots:0,firstDock:null,end:null};
    this.world={w:4800,h:3600};
    this.planets=[{x:2200,y:1800,r:260,influence:900,mu:780000,color:'#3b8dff',name:'Olbrzym Błękitny'},{x:3800,y:900,r:125,influence:520,mu:300000,color:'#e08aff',name:'Księżyc Fuksja'}];
    this.stations=this.mission.stations.map(st=>({...st}));
    this.dust=[{x:3000,y:1700,rx:520,ry:260}]; this.asteroids=[];
    for(let i=0;i<this.mission.asteroids;i++){const p=this.planets[i%2],rad=p.r+150+(i%6)*42,a=i/12*Math.PI*4;this.asteroids.push({planet:i%2,rad,a,speed:(i%2?-.12:.09),r:14+(i%3)*5,x:p.x+Math.cos(a)*rad,y:p.y+Math.sin(a)*rad,vx:0,vy:0});}
    const start=this.stations[0];this.ship={x:start.x,y:start.y,vx:0,vy:0,a:this.mission.angle||0,r:14,hull:100,cargo:100}; this.route=1; this.ghost=this.loadGhost(); this.trace=[]; this.ghostTrace=[];
    this.onKeyDown=e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='KeyF'&&!this.keys[e.code]){this.assist=!this.assist;this.telemetry.assistToggles++;this.say(`Flight Assist ${this.assist?'włączony':'wyłączony'}.`)}if(e.code==='KeyH'&&!this.keys[e.code])this.say('Klakson działa. Próżnia pozostaje niewzruszona.');this.keys[e.code]=true};
    this.onKeyUp=e=>this.keys[e.code]=false; this.onResize=()=>this.resize(); addEventListener('keydown',this.onKeyDown);addEventListener('keyup',this.onKeyUp);addEventListener('resize',this.onResize);this.resize();this.updateHUD();
  }
  resize(){const d=devicePixelRatio||1;this.canvas.width=innerWidth*d;this.canvas.height=innerHeight*d;this.canvas.style.width=innerWidth+'px';this.canvas.style.height=innerHeight+'px';this.ctx.setTransform(d,0,0,d,0,0);this.w=innerWidth;this.h=innerHeight}
  setInput(code,value){this.keys[code]=value}
  dominant(x,y){let best=null,score=0;for(const p of this.planets){const d=Math.hypot(x-p.x,y-p.y);const s=d<p.influence?p.mu/(d*d+40000):0;if(s>score){score=s;best=p}}return best}
  gravity(x,y){const p=this.dominant(x,y);if(!p)return{x:0,y:0,body:null};const dx=p.x-x,dy=p.y-y,d=Math.hypot(dx,dy),edge=Math.min(1,(p.influence-d)/(p.influence*.2));const a=Math.min(75,p.mu/(d*d+40000))*Game.smoothstep(edge);return{x:dx/d*a,y:dy/d*a,body:p}}
  predict(){let s={...this.ship},out=[];for(let i=0;i<30;i++){for(let j=0;j<5;j++){const g=this.gravity(s.x,s.y);s.vx+=g.x/60;s.vy+=g.y/60;s.x+=s.vx/60;s.y+=s.vy/60}let level='free';for(const p of this.planets){const d=Math.hypot(s.x-p.x,s.y-p.y);if(d<p.r+8)level='hit';else if(d<p.r+70&&level!=='hit')level='danger';else if(d<p.influence&&level==='free')level='orbit'}out.push({x:s.x,y:s.y,level})}return out}
  update(dt){if(this.paused)return;this.time+=dt;this.damageCd=Math.max(0,this.damageCd-dt);const s=this.ship;let thrust=0;
    if(this.keys.KeyA||this.keys.ArrowLeft)s.a-=3.2*dt;if(this.keys.KeyD||this.keys.ArrowRight)s.a+=3.2*dt;
    if(this.keys.KeyW||this.keys.ArrowUp)thrust=105;if(this.keys.KeyS||this.keys.ArrowDown){thrust=-92;this.telemetry.brakeTicks++}
    s.vx+=Math.cos(s.a)*thrust*dt;s.vy+=Math.sin(s.a)*thrust*dt;const str=(this.keys.KeyQ?-1:0)+(this.keys.KeyE?1:0);if(str){s.vx+=Math.cos(s.a+Math.PI/2)*75*str*dt;s.vy+=Math.sin(s.a+Math.PI/2)*75*str*dt;this.telemetry.strafeTicks++}
    if(this.assist&&!thrust){const fx=Math.cos(s.a),fy=Math.sin(s.a),lat=-s.vx*fy+s.vy*fx,k=Math.min(1,1.1*dt);s.vx+=lat*fy*k;s.vy-=lat*fx*k}
    const g=this.gravity(s.x,s.y);s.vx+=g.x*dt;s.vy+=g.y*dt;let speed=Math.hypot(s.vx,s.vy),cap=g.body?200:160;if(speed>cap){const excess=speed-cap,f=1-Math.min(excess/speed,1)*.8*dt;s.vx*=f;s.vy*=f}
    s.x+=s.vx*dt;s.y+=s.vy*dt;s.x=Math.max(20,Math.min(this.world.w-20,s.x));s.y=Math.max(20,Math.min(this.world.h-20,s.y));
    for(const a of this.asteroids){a.a+=a.speed*dt;const p=this.planets[a.planet],oldx=a.x,oldy=a.y;a.x=p.x+Math.cos(a.a)*a.rad;a.y=p.y+Math.sin(a.a)*a.rad;a.vx=(a.x-oldx)/dt;a.vy=(a.y-oldy)/dt;this.collide(a,a.r,22)}
    for(const p of this.planets)this.collide(p,p.r,55);
    const dusty=this.dust.some(d=>((s.x-d.x)/d.rx)**2+((s.y-d.y)/d.ry)**2<1);if(dusty){s.vx*=1-.18*dt;s.vy*=1-.18*dt}
    this.cargoRule(dt,Math.hypot(g.x,g.y));this.checkSlingshot(g.body);this.checkDock();this.trace.push({x:s.x,y:s.y});if(this.trace.length>2400)this.trace.shift();this.updateHUD();if(s.hull<=0||s.cargo<=0)this.finish(false,s.hull<=0?'Statek przeszedł na emeryturę w częściach.':'Ładunek utracił sens handlowy.');
  }
  cargoRule(dt,acc){if(this.contract.rule==='fragile'&&acc>18)this.ship.cargo-=dt*(acc-18)*.35;if(this.contract.rule==='goose'&&Math.floor(this.time)%12===11){this.ship.a+=dt*.9;if(Math.floor(this.time*10)%10===0)this.say('Gęś przejęła stery. Oczywiście.')}if(this.contract.rule==='singularity'&&Math.floor(this.time)%9>6){for(const a of this.asteroids){const dx=this.ship.x-a.x,dy=this.ship.y-a.y,d=Math.hypot(dx,dy);if(d<500){a.a+=.08*dt*(dx+dy>0?1:-1)}}}}
  collide(o,r,base){const s=this.ship,dx=s.x-o.x,dy=s.y-o.y,d=Math.hypot(dx,dy);if(d<r+s.r&&this.damageCd<=0){const ovx=o.vx||0,ovy=o.vy||0,rel=Math.hypot(s.vx-ovx,s.vy-ovy),damage=Math.max(2,rel/8+base/10);s.hull-=damage;s.cargo-=damage*.38;this.damageCd=.5;this.telemetry.collisions.push(Math.round(rel));const nx=dx/(d||1),ny=dy/(d||1);s.x=o.x+nx*(r+s.r+2);s.y=o.y+ny*(r+s.r+2);s.vx=nx*60;s.vy=ny*60;this.say(rel>100?'To nie było dokowanie.':'Tylko kosmetyczna rysa. Prawie.')}}
  checkSlingshot(body){const speed=Math.hypot(this.ship.vx,this.ship.vy);if(body&&!this.slingshot)this.slingshot={body,min:9999,entry:speed};if(this.slingshot){const d=Math.hypot(this.ship.x-this.slingshot.body.x,this.ship.y-this.slingshot.body.y);this.slingshot.min=Math.min(this.slingshot.min,d);if(!body){if(this.slingshot.min<this.slingshot.body.r+190&&speed>this.slingshot.entry*1.05){this.style=Math.min(4,this.style+.5);this.bestSling=Math.max(this.bestSling,Math.round(speed));this.telemetry.slingshots++;this.say(this.slingshot.min<this.slingshot.body.r+80?'O włos! Mnożnik rośnie.':'Elegancki Łuk!')}this.slingshot=null}}}
  checkDock(){const st=this.stations[this.route],d=Math.hypot(this.ship.x-st.x,this.ship.y-st.y),speed=Math.hypot(this.ship.vx,this.ship.vy);if(d<100&&speed<48){this.dockProgress+=Game.FIXED_DT;if(this.dockProgress>.65){if(!this.telemetry.firstDock)this.telemetry.firstDock=Math.round(this.time*10)/10;this.say(`${st.name}: dokowanie przyjęte.`);this.ship.hull=Math.min(100,this.ship.hull+12);this.route++;this.dockProgress=0;if(this.route>=this.stations.length)this.finish(true)}}else this.dockProgress=Math.max(0,this.dockProgress-Game.FIXED_DT*2);this.ui.prompt.classList.toggle('hidden',d>=180);this.ui.prompt.textContent=d<100?(speed<48?`DOKOWANIE ${Math.round(this.dockProgress/.65*100)}%`:`ZWOLNIJ · ${Math.round(speed)} / 48`):`STACJA ${Math.round(d)} m`}
  say(t){this.ui.radioText.textContent=t;this.radioUntil=this.time+4}
  updateHUD(){const s=this.ship,st=this.stations[Math.min(this.route,this.stations.length-1)];this.ui.objective.textContent=st.name;this.ui.distance.textContent=Math.round(Math.hypot(s.x-st.x,s.y-st.y))+' m';this.ui.hull.value=Math.max(0,s.hull);this.ui.cargo.value=Math.max(0,s.cargo);this.ui.hullText.textContent=Math.round(s.hull)+'%';this.ui.cargoText.textContent=Math.round(s.cargo)+'%';this.ui.timer.textContent=Game.formatTime(this.time);this.ui.style.textContent=`STYL ×${this.style.toFixed(1)}`;this.ui.assist.textContent=`ASSIST: ${this.assist?'ON':'OFF'}`;this.ui.radio.classList.toggle('hidden',this.time>this.radioUntil)}
  finish(ok,quip='Kontrola lotu udaje, że cały czas wierzyła w sukces.'){if(!this.running)return;this.running=false;this.telemetry.end=ok?'complete':'failed';const result={ok,time:this.time,hull:this.ship.hull,cargo:this.ship.cargo,style:this.style,bestSling:this.bestSling,trace:this.trace,telemetry:this.telemetry,contract:this.contract,assist:this.assist,quip};if(ok)this.saveGhost(result);this.onEnd(result)}
  loadGhost(){try{return JSON.parse(localStorage.getItem(`orbital-ghost-${this.mission.id}`))}catch{return null}}
  saveGhost(r){try{const old=this.loadGhost();if(!old||r.time<old.time)localStorage.setItem(`orbital-ghost-${this.mission.id}`,JSON.stringify({time:r.time,trace:r.trace.filter((_,i)=>i%3===0),assist:r.assist}))}catch{}}
  draw(){const c=this.ctx;c.clearRect(0,0,this.w,this.h);c.fillStyle='#030812';c.fillRect(0,0,this.w,this.h);const look=Game.cameraLookAhead(this.ship.vx,this.ship.vy,Math.min(this.w,this.h)*.13),cam={x:this.ship.x-this.w/2+look.x,y:this.ship.y-this.h/2+look.y};c.save();c.translate(-cam.x,-cam.y);this.drawStars(c,cam);c.strokeStyle='#5de6ff22';c.setLineDash([8,12]);c.beginPath();for(let i=this.route;i<this.stations.length;i++){const p=this.stations[i];if(i===this.route)c.moveTo(this.ship.x,this.ship.y);c.lineTo(p.x,p.y)}c.stroke();c.setLineDash([]);
    for(const d of this.dust){c.fillStyle='#a477c818';c.beginPath();c.ellipse(d.x,d.y,d.rx,d.ry,0,0,7);c.fill();c.strokeStyle='#c9a0ff33';for(let y=-2;y<=2;y++){c.beginPath();c.moveTo(d.x-d.rx*.7,d.y+y*55);c.lineTo(d.x+d.rx*.7,d.y+y*55+25);c.stroke()}}
    for(const p of this.planets){c.strokeStyle=p.color+'44';c.lineWidth=2;c.beginPath();c.arc(p.x,p.y,p.influence,0,7);c.stroke();c.fillStyle=p.color+'22';c.beginPath();c.arc(p.x,p.y,p.r+55,0,7);c.fill();c.fillStyle=p.color;c.beginPath();c.arc(p.x,p.y,p.r,0,7);c.fill();c.strokeStyle='#ffffff55';c.lineWidth=8;c.stroke()}
    for(let i=0;i<this.stations.length;i++){const s=this.stations[i];c.strokeStyle=i===this.route?s.color:'#527080';c.lineWidth=4;c.beginPath();c.arc(s.x,s.y,75,0,7);c.stroke();c.fillStyle=s.color;c.fillRect(s.x-28,s.y-9,56,18);c.fillRect(s.x-8,s.y-28,16,56);c.fillStyle='#eaf7ff';c.font='bold 13px monospace';c.fillText(s.name,s.x-55,s.y-90)}
    for(const a of this.asteroids){c.fillStyle='#7f91a0';c.beginPath();c.arc(a.x,a.y,a.r,0,7);c.fill()}
    if(this.ghost?.trace){c.strokeStyle='#5de6ff55';c.lineWidth=3;c.beginPath();this.ghost.trace.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke()}
    const pred=this.predict();for(const p of pred){c.fillStyle={free:'#fff',orbit:'#5de6ff',danger:'#ffc65c',hit:'#ff6577'}[p.level];c.beginPath();c.arc(p.x,p.y,3,0,7);c.fill()}
    c.translate(this.ship.x,this.ship.y);c.rotate(this.ship.a);c.fillStyle='#eaf7ff';c.strokeStyle='#5de6ff';c.lineWidth=3;c.beginPath();c.moveTo(20,0);c.lineTo(-14,11);c.lineTo(-8,0);c.lineTo(-14,-11);c.closePath();c.fill();c.stroke();if(this.keys.KeyW||this.keys.ArrowUp){c.fillStyle='#b7ff5a';c.beginPath();c.moveTo(-10,-6);c.lineTo(-28,0);c.lineTo(-10,6);c.fill()}c.restore();this.drawMap()}
  drawStars(c,cam){for(const layer of [{n:70,f:.12,color:'#7cb9df55',r:1},{n:45,f:.3,color:'#ffffff88',r:1.6},{n:18,f:.55,color:'#b7e9ffbb',r:2.2}]){c.fillStyle=layer.color;for(let i=0;i<layer.n;i++){const sx=Game.wrap(i*977-cam.x*layer.f,this.w+120)-60,sy=Game.wrap(i*577-cam.y*layer.f,this.h+120)-60;c.beginPath();c.arc(cam.x+sx,cam.y+sy,layer.r,0,7);c.fill()}}}
  drawMap(){const c=this.mctx,w=this.map.width,h=this.map.height,s=Math.min(w/this.world.w,h/this.world.h);c.clearRect(0,0,w,h);c.save();c.scale(s,s);for(const p of this.planets){c.fillStyle=p.color;c.beginPath();c.arc(p.x,p.y,p.r,0,7);c.fill()}for(let i=0;i<this.stations.length;i++){c.fillStyle=i===this.route?'#b7ff5a':'#789';c.fillRect(this.stations[i].x-30,this.stations[i].y-30,60,60)}c.fillStyle='#fff';c.beginPath();c.arc(this.ship.x,this.ship.y,35,0,7);c.fill();c.restore()}
  loop=t=>{if(!this.running)return;if(!this.last)this.last=t;this.acc+=Math.min((t-this.last)/1000,.25);this.last=t;while(this.acc>=Game.FIXED_DT){this.update(Game.FIXED_DT);this.acc-=Game.FIXED_DT}this.draw();requestAnimationFrame(this.loop)};
  start(){this.running=true;this.say(`Ładunek: ${this.contract.name}. Pierwszy cel na kursie.`);requestAnimationFrame(this.loop)}
  destroy(){this.running=false;removeEventListener('keydown',this.onKeyDown);removeEventListener('keyup',this.onKeyUp);removeEventListener('resize',this.onResize)}
}
Game.FIXED_DT=1/60;Game.MAX_FRAME_TIME=.25;Game.CONTRACTS=[{id:'jelly',icon:'🫙',name:'Galaretka kwantowa',rule:'fragile',desc:'Nie znosi przeciążeń. Bliski łuk daje styl, ale zabiera integralność.',reward:'1 800 KR'},{id:'goose',icon:'🪿',name:'Jedna bardzo zła gęś',rule:'goose',desc:'Co 12 sekund próbuje przejąć stery. Tak, klatka jest zamknięta.',reward:'2 200 KR'},{id:'singularity',icon:'⚫',name:'Kieszonkowa osobliwość',rule:'singularity',desc:'Okresowo przyciąga pobliski gruz. Absolutnie legalna.',reward:'2 700 KR'}];
const C=Game.CONTRACTS,S=(x,y,name,color='#b7ff5a')=>({x,y,name,color});Game.MISSIONS=[
{id:'license',seed:501,icon:'🛰️',name:'Licencja kurierska',difficulty:1,asteroids:4,contract:C[1],desc:'Krótki lot bez obowiązkowego slingshota.',brief:'Naucz się rozpędzać, hamować i utrzymać niską prędkość przez zielony pierścień.',stations:[S(700,1800,'PORT START'),S(1350,1800,'PORT LICENCJA')]},
{id:'first-arc',seed:502,icon:'🔵',name:'Pierwszy łuk',difficulty:1,asteroids:7,contract:C[0],desc:'Obejdź Błękitnego Olbrzyma.',brief:'Bezpieczna trasa prowadzi górą. Pole grawitacyjne może dać szybszy, bardziej stylowy przelot.',stations:[S(1050,1150,'PORT START'),S(2200,650,'BAR APOGEUM','#ffc65c'),S(3150,1200,'PUNKT ŁUK')]},
{id:'debris',seed:503,icon:'☄️',name:'Pas gruzu',difficulty:2,asteroids:12,contract:C[1],desc:'Trzy dokowania wśród asteroid.',brief:'Patrz na predykcję toru i nie przecinaj orbit odłamków bez planu.',stations:[S(700,1800,'PORT START'),S(1500,1100,'WARSZTAT','#ffc65c'),S(2800,1050,'SKŁAD 12','#5de6ff'),S(3500,1700,'META GRUZ')]},
{id:'dust-run',seed:504,icon:'🌫️',name:'Kurier we mgle',difficulty:2,asteroids:10,contract:C[0],desc:'Skrót przez hamującą chmurę pyłu.',brief:'Pył wytraca prędkość. Możesz użyć go jako hamulca przed dokowaniem albo ominąć od południa.',stations:[S(900,2200,'PORT START'),S(2450,2050,'BOJA PYŁOWA','#ffc65c'),S(3650,2000,'LAB 7','#5de6ff')]},
{id:'goose-express',seed:505,icon:'🪿',name:'Gęsi ekspres',difficulty:3,asteroids:12,contract:C[1],desc:'Długa trasa, a pasażer walczy ze sterami.',brief:'Co dwanaście sekund gęś skręca statek. Kontruj obrót, nie próbuj walczyć z nim ciągiem.',stations:[S(650,2850,'PORT START'),S(1500,2300,'KIOSK'),S(2350,1250,'BAR APOGEUM','#ffc65c'),S(3600,1150,'LAB 7','#5de6ff'),S(3900,2250,'META GĘSI')]},
{id:'event-horizon',seed:506,icon:'⚫',name:'Horyzont dostawy',difficulty:3,asteroids:16,contract:C[2],desc:'Finałowa trasa przez oba pola grawitacyjne.',brief:'Osobliwość porusza gruz. Zachowaj zapas kadłuba i wybierz ciasny łuk dopiero, gdy droga jest wolna.',stations:[S(650,950,'PORT START'),S(1750,700,'BOJA ALFA','#ffc65c'),S(2900,1050,'LAB 7','#5de6ff'),S(4000,1500,'BRAMA FUKSJA','#e08aff'),S(3300,2850,'META KURIERSKA')] }];
Game.smoothstep=t=>{t=Math.max(0,Math.min(1,t));return t*t*(3-2*t)};Game.cameraLookAhead=(vx,vy,max)=>{const s=Math.hypot(vx,vy);return s?{x:vx/s*Math.min(max,s*.55),y:vy/s*Math.min(max,s*.55)}:{x:0,y:0}};Game.formatTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;Game.mulberry32=a=>()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296};
Game.segCircleIntersect=(x1,y1,x2,y2,cx,cy,r)=>{const dx=x2-x1,dy=y2-y1,fx=x1-cx,fy=y1-cy,a=dx*dx+dy*dy,b=2*(fx*dx+fy*dy),c=fx*fx+fy*fy-r*r,d=b*b-4*a*c;if(d<0)return false;const q=Math.sqrt(d);return(-b-q)/(2*a)>=0&&(-b-q)/(2*a)<=1||(-b+q)/(2*a)>=0&&(-b+q)/(2*a)<=1};Game.wrap=(v,s)=>((v%s)+s)%s;Game.wrappedDelta=(a,b,s)=>{let d=b-a;if(d>s/2)d-=s;if(d<-s/2)d+=s;return d};Game.wrappedDistance=(a,b,w,h=w)=>Math.hypot(Game.wrappedDelta(a.x,b.x,w),Game.wrappedDelta(a.y,b.y,h));
if(typeof window!=='undefined')window.Game=Game;if(typeof module!=='undefined')module.exports=Game;
