'use strict';
const $=id=>document.getElementById(id),screens=[...document.querySelectorAll('.screen')];
const ui={objective:$('objective'),distance:$('distance'),hull:$('hull'),cargo:$('cargo'),hullText:$('hullText'),cargoText:$('cargoText'),timer:$('timer'),style:$('style'),assist:$('assist'),radio:$('radio'),radioText:$('radioText'),prompt:$('prompt')};
let game=null,selected=Game.MISSIONS[0],muted=localStorage.getItem('orbital-muted')==='1';
function show(id){screens.forEach(s=>s.classList.toggle('hidden',s.id!==id))}
function gameChrome(on){['hud','minimap','touchControls'].forEach(id=>$(id).classList.toggle('hidden',!on));if(!on){$('radio').classList.add('hidden');$('prompt').classList.add('hidden')}}
function missionBest(id){try{return JSON.parse(localStorage.getItem(`orbital-ghost-${id}`))}catch{return null}}
function renderMissions(){const root=$('contractCards');root.innerHTML='';Game.MISSIONS.forEach((m,i)=>{const best=missionBest(m.id),b=document.createElement('button');b.className='card';b.innerHTML=`${best?'<span class="done">✓</span>':''}<i>${m.icon}</i><span class="difficulty">MISJA ${i+1} · ${'★'.repeat(m.difficulty)}${'☆'.repeat(3-m.difficulty)}</span><h3>${m.name}</h3><p>${m.desc}</p><strong>${m.stations.length-1} dok. · ${m.contract.name}${best?` · ${Game.formatTime(best.time)}`:''}</strong>`;b.onclick=()=>selectMission(m);root.appendChild(b)})}
function selectMission(m){selected=m;$('briefingLabel').textContent=`MISJA ${Game.MISSIONS.indexOf(m)+1} · ${m.contract.name}`;$('briefingTitle').textContent=m.name;$('briefingDesc').textContent=m.brief;$('briefingMeta').innerHTML=`<span>${m.stations.length-1} DOKOWANIA</span><span>${'★'.repeat(m.difficulty)} TRUDNOŚĆ</span><span>${m.contract.reward}</span>`;show('briefing')}
function start(){if(game)game.destroy();show(null);gameChrome(true);game=new Game($('game'),$('minimap'),ui,{mission:selected,onEnd:summary});game.start()}
function summary(r){gameChrome(false);$('summaryLabel').textContent=r.ok?'MISJA UKOŃCZONA':'MISJA PRZERWANA';$('summaryTitle').textContent=r.ok?'Przesyłka dostarczona!':'Orbita wygrała tę rundę';$('summaryStats').innerHTML=`<div><span>CZAS</span><b>${Game.formatTime(r.time)}</b></div><div><span>ŁADUNEK</span><b>${Math.max(0,Math.round(r.cargo))}%</b></div><div><span>STYL</span><b>×${r.style.toFixed(1)}</b></div><div><span>SLINGSHOT</span><b>${r.bestSling||'—'} px/s</b></div>`;$('summaryQuip').textContent=r.quip;show('summary');renderMissions();refreshBest()}
function home(){if(game){game.destroy();game=null}gameChrome(false);show('menu');refreshBest()}
function refreshBest(){let best=null;for(const m of Game.MISSIONS){const x=missionBest(m.id);if(x&&(!best||x.time<best.time))best={...x,name:m.name}}$('best').textContent=best?`Rekord: ${Game.formatTime(best.time)} · ${best.name}`:'Brak ukończonych tras'}
function tone(){if(muted)return;const A=window.AudioContext||window.webkitAudioContext,a=new A,o=a.createOscillator(),g=a.createGain();o.frequency.value=520;g.gain.value=.035;o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.08)}
$('play').onclick=()=>{tone();renderMissions();show('contracts')};$('how').onclick=()=>show('help');$('launch').onclick=start;$('briefingBack').onclick=()=>show('contracts');$('again').onclick=start;$('resume').onclick=()=>{show(null);game.paused=false;game.last=performance.now();gameChrome(true)};$('restart').onclick=start;ui.assist.onclick=()=>{if(game){game.assist=!game.assist;game.updateHUD()}};
document.querySelectorAll('.back').forEach(b=>b.onclick=()=>show('menu'));document.querySelectorAll('.home').forEach(b=>b.onclick=home);
$('mute').onclick=()=>{muted=!muted;localStorage.setItem('orbital-muted',muted?'1':'0');$('mute').textContent=`DŹWIĘK: ${muted?'OFF':'ON'}`};
addEventListener('keydown',e=>{if(e.code==='Escape'&&game?.running){game.paused=!game.paused;if(game.paused){gameChrome(false);show('pause')}else{show(null);gameChrome(true);game.last=performance.now()}}});
document.querySelectorAll('#touchControls [data-key]').forEach(b=>{const set=value=>{if(game&&!game.paused)game.setInput(b.dataset.key,value);b.classList.toggle('active',value)};b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);set(true)});['pointerup','pointercancel','lostpointercapture'].forEach(n=>b.addEventListener(n,()=>set(false)))});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game?.running&&!game.paused){game.paused=true;gameChrome(false);show('pause')}});
$('mute').textContent=`DŹWIĘK: ${muted?'OFF':'ON'}`;renderMissions();refreshBest();gameChrome(false);
