import test from 'node:test';import assert from 'node:assert/strict';
import {license01,validateMission,mulberry32} from '../src/missions.mjs';
import {FIXED_DT,influenceAt,dominantGravity,integrateShip,predict,classifyTrajectory,dockingStatus,makeState,step,runTrace,asteroidPosition,SIM_VERSION} from '../src/simulation.mjs';
import {InputController} from '../src/input.mjs';import {saveGhost,loadGhost,memoryStorage} from '../src/storage.mjs';import {TRANSITIONS} from '../src/app.mjs';

test('mission schema, seeded PRNG and authored object budget are deterministic',()=>{assert.equal(validateMission(license01),true);assert.equal(license01.asteroids.length,8);assert.deepEqual([mulberry32(7)(),mulberry32(7)()],[mulberry32(7)(),mulberry32(7)()]);});
test('160 px/s moves exactly 160 px in one second independent of renderer',()=>{const s={x:0,y:0,vx:160,vy:0,angle:0,assist:false,lastGravity:0};const p={x:9999,y:9999,influence:1,radius:1,mu:0,softening:1,maxAccel:0};for(let i=0;i<60;i++)integrateShip(s,{},p,FIXED_DT);assert.ok(Math.abs(s.x-160)<1e-9);});
test('gravity fades at influence edge and stays finite at center',()=>{const p=license01.planet;assert.equal(influenceAt(p,{x:p.x+p.influence,y:p.y}).strength,0);assert.ok(influenceAt(p,{x:p.x+p.influence*.9,y:p.y}).strength>0);const c=influenceAt(p,p);assert.ok(Number.isFinite(c.strength)&&Number.isFinite(c.x));});
test('dominant gravity selects the strongest body',()=>{const base={y:0,radius:1,influence:500,mu:10000,softening:10,maxAccel:100};const g=dominantGravity([{...base,id:'far',x:300},{...base,id:'near',x:30}],{x:0,y:0});assert.equal(g.body.id,'near');});
test('Assist Lite removes lateral component but Assist Off preserves it',()=>{const p={...license01.planet,influence:0};const on={x:0,y:0,vx:0,vy:50,angle:0,assist:true,lastGravity:0};const off={...on,assist:false};integrateShip(on,{},p,1);integrateShip(off,{},p,1);assert.ok(on.vy<off.vy);assert.equal(off.vy,50);});
test('braking reaches near zero in configured 1.5–2 second window',()=>{const p={...license01.planet,influence:0};const s={x:0,y:0,vx:160,vy:0,angle:0,assist:true,lastGravity:0};for(let i=0;i<100;i++)integrateShip(s,{brake:true},p,FIXED_DT);assert.ok(Math.abs(s.vx)<1);});
test('prediction uses integration without mutating ship and matches actual coast',()=>{const ship={x:1200,y:1700,vx:80,vy:20,angle:.2,assist:false,lastGravity:0};const before={...ship},points=predict(ship,license01.planet);assert.deepEqual(ship,before);const actual={...ship};for(let i=0;i<150;i++)integrateShip(actual,{},license01.planet,FIXED_DT);assert.ok(Math.hypot(actual.x-points.at(-1).x,actual.y-points.at(-1).y)<1e-7);});
test('trajectory collision classification is semantic',()=>{const p=license01.planet;assert.equal(classifyTrajectory([{x:p.x,y:p.y}],p),'collision');assert.equal(classifyTrajectory([{x:0,y:0}],p),'free');});
test('docking requires range, relative speed and 0.65 s hold',()=>{const station=license01.stations[0],ship={x:station.x,y:station.y,vx:0,vy:0};let progress=0,r;for(let i=0;i<39;i++){r=dockingStatus(ship,station,progress);progress=r.progress;}assert.equal(r.docked,true);assert.equal(dockingStatus({...ship,vx:100},station,0).message,'ZWOLNIJ');});
test('asteroid contact applies one impact then 0.5 s cooldown',()=>{const m={...license01,stations:license01.stations.map(s=>({...s,x:4000,y:4000})),asteroids:[license01.asteroids[0]]};const state=makeState(m);const a=asteroidPosition(m.asteroids[0],m.planet,0);Object.assign(state.ship,{x:a.x,y:a.y,vx:0,vy:0});step(state,{},m);const hull=state.hull;step(state,{},m);assert.equal(state.hull,hull);assert.ok(hull<100);});
test('same mission and input trace produces identical state',()=>{const inputs=Array.from({length:600},(_,i)=>({thrust:i<240,right:i>=240&&i<300,brake:i>500}));assert.deepEqual(runTrace(license01,{assist:true,inputs},600),runTrace(license01,{assist:true,inputs},600));});
test('ghost refuses incompatible mission, version or assist',()=>{const store=memoryStorage(),state=makeState(license01,true);const g=saveGhost(store,license01,state,[[1,2,3]]);assert.equal(g.simulation,SIM_VERSION);assert.equal(loadGhost(store,license01,true).samples.length,1);assert.equal(loadGhost(store,license01,false),null);assert.equal(loadGhost(store,{...license01,seed:1},true),null);});
test('input mapping attaches only once, maps keys, and cleans listeners',()=>{const listeners=new Map(),target={addEventListener:(k,v)=>listeners.set(k,v),removeEventListener:(k,v)=>{if(listeners.get(k)===v)listeners.delete(k)}};const input=new InputController(target);input.attach();input.attach();listeners.get('keydown')({code:'ArrowUp',preventDefault(){}});assert.equal(input.snapshot().thrust,true);input.detach();assert.equal(listeners.size,0);assert.equal(input.attachCount,0);});
test('explicit app state machine covers full lifecycle and rejects duplicate starts by design',()=>{assert.deepEqual(TRANSITIONS.menu,['contract']);assert.ok(TRANSITIONS.playing.includes('paused'));assert.ok(TRANSITIONS.paused.includes('playing'));assert.ok(TRANSITIONS.summary.includes('briefing'));});
