import {stage2Mission,validateMission,CONTRACTS,contractById} from './missions.mjs';import {FIXED_DT,makeState,step,predict,classifyTrajectory,stationDecision,calculateScore} from './simulation.mjs';import {InputController} from './input.mjs';import {Renderer} from './renderer.mjs';import {saveGhost,loadGhost,telemetryJSON,loadSettings,saveSettings} from './storage.mjs';import {AudioFeedback} from './audio.mjs';
export const TRANSITIONS={menu:['contract'],contract:['briefing','menu'],briefing:['playing','contract'],playing:['paused','summary','menu'],paused:['playing','menu'],summary:['briefing','menu']};
export class OrbitalApp{constructor(doc=document){this.d=doc;this.mode='menu';this.m=stage2Mission;validateMission(this.m);this.contract='jelly';this.input=new InputController(window);this.renderer=new Renderer(doc.querySelector('#game'),doc.querySelector('#minimap'));this.loop=null;this.samples=[];this.audio=new AudioFeedback(loadSettings(globalThis.localStorage));this.last=0;this.acc=0;this.bind();this.show('menu');}
 bind(){this.d.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>this.show(b.dataset.go));this.d.querySelectorAll('[data-contract]').forEach(b=>b.onclick=()=>this.selectContract(b.dataset.contract));this.d.querySelector('#assist').onchange=e=>{if(this.state)this.state.ship.assist=e.target.checked;};this.d.querySelector('#pause').onclick=()=>this.show(this.mode==='paused'?'playing':'paused');window.addEventListener('keydown',e=>{if(e.code==='Escape'&&(this.mode==='playing'||this.mode==='paused'))this.show(this.mode==='playing'?'paused':'playing');});this.d.querySelector('#classic').onclick=()=>location.href='classic.html?mode=classic';window.addEventListener('resize',()=>this.renderer.resize());this.d.querySelectorAll('[data-action]').forEach(b=>{const action=b.dataset.action;for(const e of ['pointerdown','pointerenter'])b.addEventListener(e,ev=>{if(ev.buttons||e==='pointerdown'){ev.preventDefault();this.input.setAction(action,true);}});for(const e of ['pointerup','pointercancel','pointerleave'])b.addEventListener(e,()=>this.input.setAction(action,false));});this.d.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>this.choose(b.dataset.decision));this.d.querySelector('#export').onclick=()=>this.exportTelemetry();this.d.querySelector('#debugToggle').onclick=()=>this.d.body.classList.toggle('debug');this.d.querySelectorAll('[data-volume]').forEach(i=>i.oninput=()=>{const settings={master:+this.d.querySelector('[data-volume="master"]').value,effects:+this.d.querySelector('[data-volume="effects"]').value,ui:+this.d.querySelector('[data-volume="ui"]').value};this.audio.settings=settings;saveSettings(localStorage,settings);});}
 selectContract(id){this.contract=contractById(id).id;this.d.querySelectorAll('[data-contract]').forEach(c=>c.classList.toggle('selected',c.dataset.contract===this.contract));this.d.querySelector('#contractRule').textContent=contractById(this.contract).rule;this.show('briefing');}
 show(next){if(next!==this.mode&&!TRANSITIONS[this.mode]?.includes(next))return false;this.mode=next;this.d.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===next));this.d.body.dataset.state=next;if(next==='playing'&&!this.state)this.start();if(next==='briefing'&&(this.d.body.dataset.fromSummary==='1'||this.state)){this.stop();this.state=null;this.d.body.dataset.fromSummary='0';}if(next==='summary'){this.fillSummary();this.d.body.dataset.fromSummary='1';this.stop();}return true;}
 start(){this.audio.unlock();this.startedAt=new Date().toISOString();this.state=makeState(this.m,this.d.querySelector('#assist').checked,this.contract);this.samples=[];this.input.attach();this.last=performance.now();this.acc=0;this.frame=this.frame.bind(this);this.loop=requestAnimationFrame(this.frame);}
 stop(){if(this.loop)cancelAnimationFrame(this.loop);this.loop=null;this.input.detach();}
 choose(choice){if(stationDecision(this.state,choice)){this.d.querySelector('#stationChoice').hidden=true;this.last=performance.now();this.audio.station();}}
 frame(now){if(this.mode!=='playing')return;this.acc+=Math.min(.1,(now-this.last)/1000);this.last=now;while(this.acc>=FIXED_DT){const controls=this.input.snapshot();step(this.state,controls,this.m);this.audio.update(this.state,controls);this.acc-=FIXED_DT;if(this.state.tick%6===0)this.samples.push([this.state.tick,+this.state.ship.x.toFixed(2),+this.state.ship.y.toFixed(2)]);if(this.state.awaitingDecision){this.d.querySelector('#stationChoice').hidden=false;break;}if(this.state.completed||this.state.hull<=0||this.state.cargo<=0||this.state.time>=this.m.timeLimit){this.show('summary');return;}}const kind=this.renderer.draw(this.state,this.m);this.hud(kind);this.loop=requestAnimationFrame(this.frame);}
 hud(kind){const s=this.state,target=this.m.stations[Math.min(s.stationIndex,3)],dist=Math.round(Math.hypot(s.ship.x-target.x,s.ship.y-target.y)),leg=this.m.legs[Math.min(s.stationIndex,3)];this.d.querySelector('#objective').textContent=`${leg.title} · ${target.name} · ${dist} m`;this.d.querySelector('#hull').textContent=`KADŁUB ${Math.round(s.hull)}%`;this.d.querySelector('#cargo').textContent=`ŁADUNEK ${Math.round(s.cargo)}%`;this.d.querySelector('#cargoRule').textContent=s.cargoStatus;this.d.querySelector('#time').textContent=`${Math.floor(s.time/60)}:${String(Math.floor(s.time%60)).padStart(2,'0')}`;this.d.querySelector('#style').textContent=`STYL ×${s.style.toFixed(2)}`;this.d.querySelector('#dock').textContent=s.dockMessage||'';this.d.querySelector('#warning').textContent=kind==='collision'?'KOLIZJA NA KURSIE':kind==='danger'?'NIEBEZPIECZNY PRZELOT':s.dustLevel>.1?'PYŁ · CIĄG OSŁABIONY':s.gravityEntry?'POLE GRAWITACYJNE':'';this.d.querySelector('#assistState').textContent=s.ship.assist?'ASSIST ON':'ASSIST OFF';this.d.querySelector('#debug').textContent=`FPS ${Math.round(1000/Math.max(1,performance.now()-this.last))} · TICK ${s.tick} · CIAŁO ${s.ship.gravityBody||'—'} · G ${s.ship.lastGravity.toFixed(1)} · V ${Math.hypot(s.ship.vx,s.ship.vy).toFixed(1)} · ${s.cargoStatus}`;}
 fillSummary(){const s=this.state;if(!s)return;saveGhost(localStorage,this.m,s,this.samples);const score=calculateScore(s,s.contract);this.d.querySelector('#summaryTitle').textContent=s.completed?'DOSTARCZONO!':'KONTRAKT PRZERWANY';this.d.querySelector('#summaryStats').innerHTML=`<li>Czas <b>${s.time.toFixed(1)} s</b><small>Spróbuj ciaśniejszych łuków</small></li><li>Integralność <b>${score.integrity}</b><small>Kadłub ${Math.round(s.hull)}% · ładunek ${Math.round(s.cargo)}%</small></li><li>Styl <b>${score.style}</b><small>${s.slingshot?'Legalny slingshot zaliczony':'Pole grawitacyjne da premię'}</small></li><li>Premia ${contractById(s.contract).name} <b>${score.contract}</b></li><li class="total">WYNIK <b>${score.total}</b></li><li>Ghost <b>${loadGhost(localStorage,this.m,s.ship.assist,s.contract)?.samples.length||0} próbek</b></li>`;}
 exportTelemetry(){const blob=new Blob([telemetryJSON(this.m,this.state,this.startedAt)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`orbital-telemetry-${this.m.seed}.json`;a.click();URL.revokeObjectURL(a.href);}
}
if(typeof document!=='undefined')window.orbitalApp=new OrbitalApp();
