import { predict,classifyTrajectory,asteroidPosition } from './simulation.mjs';
const C={bg:'#071526',panel:'#0d2238',goal:'#c8ff58',gravity:'#4de7f3',warn:'#ffc857',hit:'#ff6b6b',ink:'#eaf7ff',route:'#54758d'};
export class Renderer{constructor(canvas,map){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.map=map;this.mctx=map.getContext('2d');this.camera={x:0,y:0};this.resize();}resize(){const d=Math.min(devicePixelRatio||1,2),r=this.canvas.getBoundingClientRect();this.canvas.width=Math.max(1,r.width*d);this.canvas.height=Math.max(1,r.height*d);this.ctx.setTransform(d,0,0,d,0,0);this.w=r.width;this.h=r.height;}world(p){return{x:p.x-this.camera.x+this.w/2,y:p.y-this.camera.y+this.h/2};}circle(p,r,color,fill=false){const q=this.world(p),x=this.ctx; x.beginPath();x.arc(q.x,q.y,r,0,Math.PI*2);fill?x.fillStyle=color:x.strokeStyle=color;fill?x.fill():x.stroke();}
 draw(state,m){const x=this.ctx;x.clearRect(0,0,this.w,this.h);x.fillStyle=C.bg;x.fillRect(0,0,this.w,this.h);const speed=Math.hypot(state.ship.vx,state.ship.vy),look=Math.min(Math.min(this.w,this.h)*.12,speed*.35);const tx=state.ship.x+(speed?state.ship.vx/speed*look:0),ty=state.ship.y+(speed?state.ship.vy/speed*look:0);this.camera.x+=(tx-this.camera.x)*.1;this.camera.y+=(ty-this.camera.y)*.1;x.save();x.globalAlpha=.35;this.circle(m.planet,m.planet.influence,C.gravity);x.restore();this.circle(m.planet,m.planet.radius+22,'#2d8ca5',true);this.circle(m.planet,m.planet.radius,'#17607f',true);const pq=this.world(m.planet);x.fillStyle='#4aa5b5';x.beginPath();x.arc(pq.x-70,pq.y-55,m.planet.radius*.7,.2,Math.PI*1.35);x.fill();x.strokeStyle='#79ddeb';x.lineWidth=4;x.beginPath();x.arc(pq.x,pq.y,m.planet.radius+6,0,Math.PI*2);x.stroke();
 const target=m.stations[Math.min(state.stationIndex,1)];x.strokeStyle=C.route;x.lineWidth=2;x.setLineDash([5,10]);let a=this.world(state.ship),b=this.world(target);x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke();const points=predict(state.ship,m.planet),kind=classifyTrajectory(points,m.planet);x.fillStyle=kind==='collision'?C.hit:kind==='danger'?C.warn:kind==='capture'?C.gravity:C.ink;for(const p of points){const q=this.world(p);x.beginPath();x.arc(q.x,q.y,3,0,7);x.fill();}x.setLineDash([]);
 for(const asteroid of m.asteroids){const p=asteroidPosition(asteroid,m.planet,state.time);this.circle(p,asteroid.radius,'#91a9b8',true);this.circle(p,asteroid.radius,'#d5e1e8');}
 m.stations.forEach((s,i)=>this.station(s,i===state.stationIndex,i));this.ship(state.ship);this.minimap(state,m);return kind;}
 station(s,target,type){const q=this.world(s),x=this.ctx;x.save();x.translate(q.x,q.y);x.rotate(performance.now()/1800);x.strokeStyle=target?C.goal:C.ink;x.lineWidth=target?4:2;if(type===0){x.strokeRect(-34,-20,68,40);x.strokeRect(-8,-42,16,84);}else{for(let i=0;i<3;i++){x.rotate(Math.PI*2/3);x.strokeRect(15,-12,42,24);}x.beginPath();x.arc(0,0,21,0,7);x.stroke();}x.restore();this.circle(s,s.dockRadius,target?C.goal:C.route);}
 ship(s){const q=this.world(s),x=this.ctx;x.save();x.translate(q.x,q.y);x.rotate(s.angle);x.fillStyle=C.ink;x.strokeStyle='#071526';x.lineWidth=2;x.beginPath();x.moveTo(24,0);x.lineTo(-17,14);x.lineTo(-10,0);x.lineTo(-17,-14);x.closePath();x.fill();x.stroke();x.restore();}
 minimap(state,m){const x=this.mctx,w=this.map.width,h=this.map.height,sc=w/m.worldSize;x.clearRect(0,0,w,h);x.fillStyle=C.bg;x.fillRect(0,0,w,h);x.strokeStyle=C.gravity;x.beginPath();x.arc(m.planet.x*sc,m.planet.y*sc,m.planet.influence*sc,0,7);x.stroke();x.fillStyle='#24829a';x.beginPath();x.arc(m.planet.x*sc,m.planet.y*sc,m.planet.radius*sc,0,7);x.fill();for(const s of m.stations){x.fillStyle=C.goal;x.fillRect(s.x*sc-3,s.y*sc-3,6,6);}x.fillStyle=C.ink;x.beginPath();x.arc(state.ship.x*sc,state.ship.y*sc,3,0,7);x.fill();}}
