export const FIXED_DT=1/60, SIM_VERSION='flight-2';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export function influenceAt(body,p){const dx=body.x-p.x,dy=body.y-p.y,r=Math.hypot(dx,dy);if(r>=body.influence)return{x:0,y:0,strength:0,distance:r};const edge=body.influence*.2,fade=clamp((body.influence-r)/edge,0,1);const accel=Math.min(body.maxAccel,body.mu/(r*r+body.softening*body.softening))*fade;return{x:r?dx/r*accel:0,y:r?dy/r*accel:0,strength:accel,distance:r};}
export function dominantGravity(bodies,p){let best=null;for(const b of bodies){const g=influenceAt(b,p);if(!best||g.strength>best.strength)best={body:b,...g};}return best?.strength?best:null;}
export function classifyTrajectory(points,bodies){bodies=Array.isArray(bodies)?bodies:[bodies];let danger=false,capture=false;for(const p of points)for(const body of bodies){const d=Math.hypot(p.x-body.x,p.y-body.y);if(d<=body.radius)return'collision';if(d<body.radius+120)danger=true;if(d<body.influence*.72)capture=true;}return danger?'danger':capture?'capture':'free';}
function softLimit(ship,dt){const s=Math.hypot(ship.vx,ship.vy);if(s>160&&ship.lastGravity<1){const target=160+(s-160)*Math.exp(-2.4*dt);ship.vx*=target/s;ship.vy*=target/s;}if(s>205){ship.vx*=205/s;ship.vy*=205/s;}}
export function integrateShip(ship,input,bodies,dt=FIXED_DT){bodies=Array.isArray(bodies)?bodies:[bodies];const turn=(input.right?1:0)-(input.left?1:0);ship.angle+=turn*2.85*dt;const fx=Math.cos(ship.angle),fy=Math.sin(ship.angle),accel=input.thrust?105:0;ship.vx+=fx*accel*dt;ship.vy+=fy*accel*dt;if(input.brake){const speed=Math.hypot(ship.vx,ship.vy),decel=105*dt;if(speed<=decel){ship.vx=0;ship.vy=0;}else{ship.vx-=ship.vx/speed*decel;ship.vy-=ship.vy/speed*decel;}}if(ship.assist&&!input.thrust&&!input.brake){const lateral=-ship.vx*fy+ship.vy*fx,damp=lateral*(1-Math.exp(-1.25*dt));ship.vx+=fy*damp;ship.vy-=fx*damp;}const g=dominantGravity(bodies,ship);if(g){ship.vx+=g.x*dt;ship.vy+=g.y*dt;}ship.lastGravity=g?.strength||0;ship.gravityBody=g?.body.id||null;softLimit(ship,dt);ship.x+=ship.vx*dt;ship.y+=ship.vy*dt;return g||{x:0,y:0,strength:0,distance:Infinity};}
export function predict(ship,bodies,seconds=2.5,count=30){const clone={...ship},points=[],steps=Math.round(seconds/FIXED_DT),every=Math.max(1,Math.floor(steps/count));for(let i=0;i<steps;i++){integrateShip(clone,{},bodies,FIXED_DT);if((i+1)%every===0&&points.length<count)points.push({x:clone.x,y:clone.y});}return points;}
export function asteroidPosition(a,planet,time){const angle=a.phase+a.speed*time;return{x:planet.x+Math.cos(angle)*a.orbit,y:planet.y+Math.sin(angle)*a.orbit,vx:-Math.sin(angle)*a.orbit*a.speed,vy:Math.cos(angle)*a.orbit*a.speed};}
export function dockingStatus(ship,station,progress,dt=FIXED_DT){const distance=Math.hypot(ship.x-station.x,ship.y-station.y),speed=Math.hypot(ship.vx,ship.vy);if(distance>station.dockRadius)return{message:'PODEJDŹ',progress:0,docked:false};if(speed>station.maxDockSpeed)return{message:'ZWOLNIJ',progress:0,docked:false};const next=progress+dt;return{message:'UTRZYMAJ',progress:next,docked:next>=.65};}
export function dustEffect(ship,dust,dt=FIXED_DT){const distance=Math.hypot(ship.x-dust.x,ship.y-dust.y),inside=clamp((dust.radius+dust.softEdge-distance)/dust.softEdge,0,1);if(!inside)return 0;const drag=Math.max(0,1-dust.drag*inside*dt);ship.vx*=drag;ship.vy*=drag;return inside;}
export function applyCargoRule(state,contract,dt=FIXED_DT){if(contract==='jelly'){const accel=Math.abs(state.ship.lastGravity-(state.previousGravity||0))/dt;if(accel>42)state.cargo=Math.max(0,state.cargo-(accel-42)*.0025*dt);state.cargoStatus=accel>42?'GALARETKA: PRZECIĄŻENIE':'GALARETKA: STABILNA';state.previousGravity=state.ship.lastGravity;}
 if(contract==='goose'){const cycle=state.time%32;state.cargoStatus=cycle>27?'GĘŚ: IMPULS ZA '+Math.ceil(32-cycle)+' s':'GĘŚ: SPOKÓJ';if(state.time>=state.nextGooseImpulse){state.ship.vx+=Math.cos(state.ship.angle+Math.PI/2)*24;state.ship.vy+=Math.sin(state.ship.angle+Math.PI/2)*24;state.nextGooseImpulse+=32;state.events.push({type:'goose',tick:state.tick});}}
 if(contract==='singularity'){state.cargoStatus='MINI-OSOBLIWOŚĆ: GRUZ '+state.nearbyDebris;}}
export function stationDecision(state,choice){if(!state.awaitingDecision)return false;if(choice==='repair'){state.hull=Math.min(100,state.hull+24);state.time+=18;}else if(choice==='secure'){state.cargoShield=Math.min(2,state.cargoShield+1);}else if(choice==='style'){state.style+=.35;}else return false;state.decisions.push({station:state.awaitingDecision,choice,tick:state.tick});state.awaitingDecision=null;return true;}
export function calculateScore(state,contract){const success=state.completed?1:0,time=Math.max(0,720-state.time)*2,integrity=Math.round(state.cargo*8+state.hull*3),style=Math.round(state.style*250),contractBonus=success?({jelly:1200,goose:1550,singularity:1900}[contract]||0):0;return{time:Math.round(time),integrity,style,contract:contractBonus,total:Math.round(time+integrity+style+contractBonus)};}
export function makeState(mission,assist=true,contract='jelly'){return{tick:0,time:0,ship:{...mission.start,vx:0,vy:0,assist,lastGravity:0,radius:18},contract,hull:100,cargo:100,cargoShield:0,cargoStatus:'',style:1,stationIndex:0,dockProgress:0,completed:false,slingshot:false,damageCooldown:0,nextGooseImpulse:32,nearbyDebris:0,shots:[],fragments:Array.from({length:6},(_,i)=>({x:3000+i*72,y:2060+(i%3)*95,vx:0,vy:0,radius:7})),events:[],decisions:[],awaitingDecision:null,dustLevel:0,gravityEntries:0};}
export function step(state,input,mission,dt=FIXED_DT){if(state.awaitingDecision)return state;state.tick++;state.time+=dt;state.damageCooldown=Math.max(0,state.damageCooldown-dt);const before=state.ship.lastGravity,g=integrateShip(state.ship,input,mission.planets,dt);if(g.strength>10&&before<=10){state.gravityEntry=true;state.gravityEntries++;state.events.push({type:'gravity',tick:state.tick});}else state.gravityEntry=false;if(g.body&&g.distance<g.body.radius+120&&Math.hypot(state.ship.vx,state.ship.vy)>145){state.slingshot=true;state.style=Math.max(state.style,2);}
 state.dustLevel=0;for(const d of mission.dust)state.dustLevel=Math.max(state.dustLevel,dustEffect(state.ship,d,dt));
 const station=mission.stations[state.stationIndex],dock=dockingStatus(state.ship,station,state.dockProgress,dt);state.dockProgress=dock.progress;state.dockMessage=dock.message;if(dock.docked){state.stationIndex++;state.dockProgress=0;state.ship.vx*=.2;state.ship.vy*=.2;if(state.stationIndex>=mission.stations.length)state.completed=true;else state.awaitingDecision=station.id;state.events.push({type:'dock',station:station.id,tick:state.tick});}
 const positions=mission.asteroids.map(a=>({...asteroidPosition(a,mission.planets[0],state.time),radius:a.radius,id:a.id}));state.nearbyDebris=state.fragments.filter(p=>Math.hypot(state.ship.x-p.x,state.ship.y-p.y)<260).length;for(const p of positions){const d=Math.hypot(state.ship.x-p.x,state.ship.y-p.y);if(d<state.ship.radius+p.radius&&state.damageCooldown<=0){const rel=Math.hypot(state.ship.vx-p.vx,state.ship.vy-p.vy),damage=clamp(rel*.12,4,24)*(state.cargoShield?0.55:1);state.hull=Math.max(0,state.hull-damage);state.cargo=Math.max(0,state.cargo-damage*.55);if(state.cargoShield)state.cargoShield--;state.damageCooldown=.5;const nx=(state.ship.x-p.x)/(d||1),ny=(state.ship.y-p.y)/(d||1);state.ship.vx+=nx*55;state.ship.vy+=ny*55;state.lastCollision={speed:rel,tick:state.tick};state.events.push({type:'collision',tick:state.tick});}}
 for(const debris of state.fragments){if(state.contract==='singularity'){const dx=state.ship.x-debris.x,dy=state.ship.y-debris.y,d=Math.hypot(dx,dy);if(d<260&&d>1){const pull=(1-d/260)*38;debris.vx+=dx/d*pull*dt;debris.vy+=dy/d*pull*dt;}}debris.x+=debris.vx*dt;debris.y+=debris.vy*dt;debris.vx*=.998;debris.vy*=.998;}if(input.fire&&(!state.lastShot||state.time-state.lastShot>=.55)){state.lastShot=state.time;state.shots.push({x:state.ship.x,y:state.ship.y,vx:Math.cos(state.ship.angle)*310,vy:Math.sin(state.ship.angle)*310,life:1.2});}for(const shot of state.shots){shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;shot.life-=dt;for(const debris of state.fragments){const dx=debris.x-shot.x,dy=debris.y-shot.y,d=Math.hypot(dx,dy);if(d<debris.radius+4){debris.vx+=shot.vx*.34;debris.vy+=shot.vy*.34;shot.life=0;state.events.push({type:'debris-push',tick:state.tick});break;}}}state.shots=state.shots.filter(s=>s.life>0);applyCargoRule(state,state.contract,dt);return state;}
export function runTrace(mission,trace,ticks){const state=makeState(mission,trace.assist!==false,trace.contract);for(let i=0;i<ticks;i++){if(state.awaitingDecision)stationDecision(state,'secure');step(state,trace.inputs[i]||{},mission);}return state;}
