export const FIXED_DT=1/60, SIM_VERSION='flight-1';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export function influenceAt(body,p){ const dx=body.x-p.x,dy=body.y-p.y,r=Math.hypot(dx,dy); if(r>=body.influence)return {x:0,y:0,strength:0,distance:r}; const edge=body.influence*.2; const fade=clamp((body.influence-r)/edge,0,1); const accel=Math.min(body.maxAccel,body.mu/(r*r+body.softening*body.softening))*fade; return {x:r?dx/r*accel:0,y:r?dy/r*accel:0,strength:accel,distance:r}; }
export function dominantGravity(bodies,p){ let best=null; for(const b of bodies){const g=influenceAt(b,p);if(!best||g.strength>best.strength)best={body:b,...g};} return best&&best.strength?best:null; }
export function classifyTrajectory(points,planet){ let danger=false; for(const p of points){const d=Math.hypot(p.x-planet.x,p.y-planet.y);if(d<=planet.radius)return 'collision';if(d<planet.radius+120)danger=true;} return danger?'danger':points.some(p=>Math.hypot(p.x-planet.x,p.y-planet.y)<planet.influence*.72)?'capture':'free'; }
function softLimit(ship,dt){const s=Math.hypot(ship.vx,ship.vy);if(s>160&&ship.lastGravity<1){const target=160+(s-160)*Math.exp(-2.4*dt);ship.vx*=target/s;ship.vy*=target/s;} if(s>205){ship.vx*=205/s;ship.vy*=205/s;}}
export function integrateShip(ship,input,planet,dt=FIXED_DT){const turn=(input.right?1:0)-(input.left?1:0);ship.angle+=turn*2.85*dt; const fx=Math.cos(ship.angle),fy=Math.sin(ship.angle); const accel=input.thrust?105:0;ship.vx+=fx*accel*dt;ship.vy+=fy*accel*dt;if(input.brake){const speed=Math.hypot(ship.vx,ship.vy),decel=105*dt;if(speed<=decel){ship.vx=0;ship.vy=0;}else{ship.vx-=ship.vx/speed*decel;ship.vy-=ship.vy/speed*decel;}} if(ship.assist&&!input.thrust&&!input.brake){const lateral=-ship.vx*fy+ship.vy*fx;const damp=lateral*(1-Math.exp(-1.25*dt));ship.vx+=fy*damp;ship.vy-=fx*damp;} const g=influenceAt(planet,ship);ship.vx+=g.x*dt;ship.vy+=g.y*dt;ship.lastGravity=g.strength;softLimit(ship,dt);ship.x+=ship.vx*dt;ship.y+=ship.vy*dt;return g;}
export function predict(ship,planet,seconds=2.5,count=30){const clone={...ship};const points=[];const steps=Math.round(seconds/FIXED_DT),every=Math.max(1,Math.floor(steps/count));for(let i=0;i<steps;i++){integrateShip(clone,{},planet,FIXED_DT);if((i+1)%every===0&&points.length<count)points.push({x:clone.x,y:clone.y});}return points;}
export function asteroidPosition(a,planet,time){const angle=a.phase+a.speed*time;return {x:planet.x+Math.cos(angle)*a.orbit,y:planet.y+Math.sin(angle)*a.orbit,vx:-Math.sin(angle)*a.orbit*a.speed,vy:Math.cos(angle)*a.orbit*a.speed};}
export function dockingStatus(ship,station,progress,dt=FIXED_DT){const distance=Math.hypot(ship.x-station.x,ship.y-station.y),speed=Math.hypot(ship.vx,ship.vy);if(distance>station.dockRadius)return {message:'PODEJDŹ',progress:0,docked:false};if(speed>station.maxDockSpeed)return {message:'ZWOLNIJ',progress:0,docked:false};const next=progress+dt;return {message:'UTRZYMAJ',progress:next,docked:next>=.65};}
export function makeState(mission,assist=true){return {tick:0,time:0,ship:{...mission.start,vx:0,vy:0,assist,lastGravity:0,radius:18},hull:100,cargo:100,style:1,stationIndex:0,dockProgress:0,completed:false,slingshot:false,damageCooldown:0};}
export function step(state,input,mission,dt=FIXED_DT){state.tick++;state.time+=dt;state.damageCooldown=Math.max(0,state.damageCooldown-dt);const before=state.ship.lastGravity;const g=integrateShip(state.ship,input,mission.planet,dt);if(g.strength>10&&before<=10)state.gravityEntry=true;if(g.distance<mission.planet.radius+100&&Math.hypot(state.ship.vx,state.ship.vy)>150){state.slingshot=true;state.style=Math.max(state.style,2);}const station=mission.stations[state.stationIndex];const dock=dockingStatus(state.ship,station,state.dockProgress,dt);state.dockProgress=dock.progress;state.dockMessage=dock.message;if(dock.docked){state.stationIndex++;state.dockProgress=0;if(state.stationIndex>=mission.stations.length)state.completed=true;}for(const a of mission.asteroids){const p=asteroidPosition(a,mission.planet,state.time);const d=Math.hypot(state.ship.x-p.x,state.ship.y-p.y);if(d<state.ship.radius+a.radius&&state.damageCooldown<=0){const rel=Math.hypot(state.ship.vx-p.vx,state.ship.vy-p.vy),damage=clamp(rel*.12,4,24);state.hull=Math.max(0,state.hull-damage);state.cargo=Math.max(0,state.cargo-damage*.55);state.damageCooldown=.5;const nx=(state.ship.x-p.x)/(d||1),ny=(state.ship.y-p.y)/(d||1);state.ship.vx+=nx*55;state.ship.vy+=ny*55;state.lastCollision={speed:rel,tick:state.tick};}}
return state;}
export function runTrace(mission,trace,ticks){const state=makeState(mission,trace.assist!==false);for(let i=0;i<ticks;i++)step(state,trace.inputs[i]||{},mission);return state;}
